Question - 1:Create a numpy array starting from 2 till 50 with a stepsize of 3

In [15]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Question - 2
Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [10]:
lst1=np.array([int(input("\nEnter the values for list1:")) for i in range(5)])
lst2=np.array([int(input("\nEnter the values for list2:")) for i in range(5)])

arr1=np.array(lst1)
arr2=np.array(lst2)

arr=np.concatenate((arr1,arr2))
print("\nconcatenated array :",arr)

sortarr = np.sort(arr)
print("\nSorted array :",sortarr)

Enter the values for list1:8
Enter the values for list1:9
Enter the values for list1:5
Enter the values for list1:2
Enter the values for list1:3
Enter the values for list2:7
Enter the values for list2:4
Enter the values for list2:6
Enter the values for list2:1
Enter the values for list2:10

concatenated array : [ 8  9  5  2  3  7  4  6  1 10]

Sorted array : [ 1  2  3  4  5  6  7  8  9 10]


Question - 3:
Write a code snippet to find the dimensions of a ndarray and its size

In [11]:
arr = np.array([1,2,3,4,5,6])

print("\nArray Dimensions : ", arr.ndim)
 
print("\nArray Size : ", arr.size)


Array Dimensions :  1

Array Size :  6


Question - 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [13]:
# newaxis snippet:


arr = np.arange(6)
print("\nArray shape:",arr.shape)

row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)


Array shape: (6,)

Shape of 2d Array in row major : (1, 6)

Shape of 2d Array in column major : (6, 1)


In [14]:
#expand_dims snippet:


arr = np.arange(6)
print("\nArray shape:",arr.shape)
row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row_arr.shape)
col_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",col_arr.shape)


Array shape: (6,)

Shape of 2d Array in row major : (1, 6)

Shape of 2d Array in column major : (6, 1)


Question - 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [19]:

arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])

print("\nVertical Stack:", np.vstack((arr_1, arr_2)))
print("\nHorizontal Stack :", np.hstack((arr_1, arr_2)))


Vertical Stack: [[  1   4   9  16  25]
 [ 36  49  64  81 100]]

Horizontal Stack : [  1   4   9  16  25  36  49  64  81 100]


Questions 6:
How to get unique items and counts of unique items?

In [20]:
a=np.arange(1,8)
print(np.unique(a,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7]), array([1, 1, 1, 1, 1, 1, 1], dtype=int64))
